name: Developer workflow checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Initialise project
      run: dev-scripts/initialise.sh
    - name: Activate virtual environment
      run: |
        source .venv/bin/activate
        # Save virtual environment setup for subsequent Action steps
        env >> $GITHUB_ENV
        echo $PATH >> $GITHUB_PATH
    - name: Test with Tox
      run: tox -m dev
    - name: Test with Pytest
      run: pytest
    - name: Update packages
      run: dev-scripts/install-deps.sh
    - name: Package build
      run: python -m build
    - name: Pre-commit run
      run: pre-commit run
    - name: Clean
      run: dev-scripts/clean.sh
